version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      nuget-all:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-all:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/wordle-ui"
    schedule:
      interval: "weekly"
    groups:
      npm-all:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/WordleApi.Host"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/wordle-ui"
    schedule:
      interval: "weekly"
